### ISSUE TITLE
Error: https://gsa.github.io/data/dotgov-domains/2014-12-01-full.csv

### ISSUE THREAD

**Issue by lboening** [GSA/data#10] opened 2015-02-15 12:51 UTC
This does not return a file.

**Comment by konklone** [comment] 2015-02-15 18:40
The issue is we have two repos using GitHub Pages competing for the same URL. :( So whenever one gets updated, it reclaims supremacy.

@gbinal Weren't you addressing this issue?

**Comment by lboening** [comment] 2015-02-17 13:45
Perhaps I am doing it wrong? Is this feasible? Github doesn't really support links to static files, does it?

**Comment by gbinal** [comment] 2015-02-18 17:28
Hi folks,  

This was my fault.  In setting up [open.gsa.gov](http://open.gsa.gov), I caused a conflict that resulted in this.  The actual conflict was over quickly but I needed to force a site rebuild to get this url working again.  This should now be done.  

@lboening - I'd say that Github does support links to static files.  It was my error that caused the interruption.

**Comment by gbinal** [comment] 2015-02-18 17:29
To confirm - https://gsa.github.io/data/dotgov-domains/2014-12-01-full.csv is resolving.

**Closed by gbinal** 2015-02-18 17:29 UTC
